### PR TITLE
Add Support for Google Chrome

### PR DESCRIPTION
**Pull request by abdallamaher**

### CODE REVIEW

**Review by HarshSingh2101 — APPROVED** [review]

**Comment by aadarshkt** [comment]
I am having a problem for your fork.

Screenshot 2022-11-08 114827

I made dist file and added backgroundScript and manifest.json. Even then is not working.

**Comment by abdallamaher** [comment]
thank you for raising this :

1. Install npm
2. Clone this Repository
3. Make Sure To use `Node 16.13.0`
4. Run `npm install`
5. Run `npm run webpack`
6. Load Extension to Google Chrome as unpacked.

**Comment by urparvezali** [comment]
it works fine..
bring support for chromium browsers and manifest v3

**Comment by pota2dev** [comment]
@abdallamaher Can you publish this on Chrome Web Store?

**Pull request closed without merging**
